# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='User',
        ),
    ]
