# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
    ]
